# Generated by Django 4.1.3 on 2022-11-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='term_check',
            field=models.BooleanField(default=False, verbose_name='약관 동의 여부'),
        ),
    ]
