# Generated by Django 4.1.3 on 2022-11-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_today_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="retention_period",
            field=models.TextField(
                choices=[("2023-11-23", "1year")],
                default="2023-11-23",
                verbose_name="회원정보 보유기간",
            ),
        ),
    ]
