# Generated by Django 4.1.3 on 2023-04-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, unique=True, verbose_name="이메일"),
                ),
                (
                    "nickname",
                    models.CharField(max_length=10, unique=True, verbose_name="닉네임"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        default="default_profile_pic.jpg",
                        upload_to="profile_pics",
                        verbose_name="프로필 사진",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="로그인 가능")),
                ("is_admin", models.BooleanField(default=False, verbose_name="어드민")),
                (
                    "point",
                    models.PositiveIntegerField(default=10000, verbose_name="포인트"),
                ),
                (
                    "is_attendance_check",
                    models.BooleanField(default=False, verbose_name="출석체크 여부"),
                ),
                (
                    "attendance_check_version",
                    models.IntegerField(default=1, verbose_name="출석체크 버전"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
