# Generated by Django 4.1.3 on 2022-11-25 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_bidder', to=settings.AUTH_USER_MODEL, verbose_name='입찰자'),
        ),
    ]
