# Generated by Django 4.1.3 on 2022-11-28 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_auction', to=settings.AUTH_USER_MODEL, verbose_name='경매 좋아요'),
        ),
    ]
