# Generated by Django 4.1.3 on 2022-11-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='image',
            new_name='b4_image',
        ),
    ]
