# Generated by Django 4.1.3 on 2022-11-23 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paintings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="painting",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author_painting",
                to=settings.AUTH_USER_MODEL,
                verbose_name="원작자",
            ),
        ),
        migrations.AlterField(
            model_name="painting",
            name="style",
            field=models.CharField(
                choices=[
                    ("01", "01_eccv16_composition_vii.t7"),
                    ("02", "02_eccv16_la_muse.t7"),
                    ("03", "03_eccv16_starry_night.t7"),
                    ("04", "04_eccv16_the_wave.t7"),
                    ("05", "05_instance_norm_candy.t7"),
                    ("06", "06_instance_norm_feathers.t7"),
                    ("07", "07_instance_norm_mosaic.t7"),
                    ("08", "08_instance_norm_the_scream.t7"),
                    ("09", "09_instance_norm_udnie.t7"),
                ],
                max_length=20,
                verbose_name="스타일",
            ),
        ),
    ]
