# Generated by Django 4.1.3 on 2022-11-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paintings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="before_img")),
            ],
            options={
                "db_table": "db_tempImg",
            },
        ),
        migrations.RemoveField(
            model_name="painting",
            name="before_image",
        ),
    ]
