# Generated by Django 4.1.3 on 2022-11-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paintings", "0002_tempimg_remove_painting_before_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="painting",
            name="before_image",
            field=models.ImageField(blank=True, upload_to="before_img"),
        ),
    ]
