# Generated by Django 4.1.3 on 2022-11-22 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_alter_painting_paint_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='paint_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paintings.paintstyle'),
        ),
    ]
