# Generated by Django 4.1.3 on 2022-11-23 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paintings", "0003_painting_before_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="painting",
            name="paint_style",
        ),
    ]
